name: Update Stats Card

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          OUTPUT_DIR: .
          TARGET_DIR: "dist"
        run: |
          python core/generative_widget.py #file moved to the core folder

      - name: Commit and Push Changes
        run: |
        
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add my-widget-light.svg my-widget-dark.svg

          #mkdir -p dist #check yet again :P

          #mv my-widget-light.svg dist/
          #mv my-widget-dark.svg dist/
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Widget auto-update"
            git push
          fi


